#!/bin/bash

# Pobierz bieżącą datę i czas w formacie 'RRRR-MM-DD HH:MM'
current_time=$(date +"%Y-%m-%d %H:%M")

# Sprawdź, czy podano argumenty i ustaw komunikat do commita
if [ "$#" -eq 0 ]; then
    commit_message="$current_time"
else
    commit_message="$current_time $*"
fi

# Wykonaj komendy Git
git add .
git commit -m "$commit_message"
git push
